import express from 'express';
import {
  issueBook,
  returnBook,
  getBookTransactions,
  getTotalRentByBook,
  getUserBooks,
  getBooksIssuedInRange,
  getAllTransactions 
} from '../controllers/transactionController.js';

const router = express.Router();

// Issue a book to a user
router.get('/', getAllTransactions );
router.post('/issue', issueBook);

// Return a book and calculate rent
router.post('/return', returnBook);

// Get users who have issued a book and its current status
router.get('/book/:bookName', getBookTransactions);

// Get total rent generated by a book
router.get('/rent/:bookName', getTotalRentByBook);

// Get all books issued to a specific user
router.get('/user/:userId', getUserBooks);

// Get books issued within a date range
router.get('/range', getBooksIssuedInRange);

export default router;
